version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

    open-pull-requests-limit: 10
    reviewers:
      - "iamvikshan"
    assignees:
      - "iamvikshan"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    # Group minor and patch updates together
    groups:
      astro-dependencies:
        patterns:
          - "astro*"
          - "@astrojs/*"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
    # Allow both direct and indirect updates
    versioning-strategy: increase
    # Ignore specific versions if needed
    # ignore:
    #   - dependency-name: "package-name"
    #     versions: ["1.x", "2.x"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    reviewers:
      - "iamvikshan"
    assignees:
      - "iamvikshan"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns:
          - "*"
