name: Sync to GitLab
on:
  push:
    branches: [main, api, dash]
  pull_request:
    types: [opened, closed, reopened]
  issues:
    types: [opened, closed, reopened]
  release:
    types: [published]
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Sync with GitLab
        uses: iamvikshan/gitsync@0a4344c52b90de2a6df63bfc9b2605fe2ae68c44 # v1.1.0
        with:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
